### ISSUE TITLE
ImportError: No module named oppy.netstatus.netstatus

### ISSUE THREAD

**Issue by d33tah** [nskinkel/oppy#141]
```
(virtualenv)[][19:18:55][/tmp/oppy/oppy]$ export PYTHONPATH=$PYTHONPATH:$(pwd)
(virtualenv)[][19:18:57][/tmp/oppy/oppy]$ ./oppy 
2015-11-20 19:18:59 INFO oppy will listen for connections on port 10050.
2015-11-20 19:18:59 INFO But we need to build some circuits first...
2015-11-20 19:18:59 INFO Retrieving network status information.
Traceback (most recent call last):
  File "./oppy", line 65, in <module>
    from oppy.netstatus.netstatus import NetStatus
ImportError: No module named oppy.netstatus.netstatus
```

**Comment by nskinkel** [comment]
Hi there.

I think this is actually an issue with the readme being unclear (some of the docs are a bit out of date at this point, see #135 ).

In your case, if you've cloned `oppy` to `/tmp`, the directory that's on your python path should be `/tmp/oppy`, **not** `/tmp/oppy/oppy`.

I've updated the README a bit to hopefully clarify this point (also, installation these days just requires a `pip -r requirements.txt` instead of manually installing `pynacl`, readme updated to clarify this as well).

That should work for you.

**Comment by d33tah** [comment]
It does, thanks.
